	CREATE TABLE Cuisine (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Name VARCHAR(25) NOT NULL,
	Description VARCHAR(100) NOT NULL
	);

	CREATE TABLE Location (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Name VARCHAR(25) NOT NULL,
	);

	CREATE TABLE User (
	Id VARCHAR(25) PRIMARY KEY NOT NULL,
	Name VARCHAR(50) UNIQUE NOT NULL,
	EmailId VARCHAR(50) UNIQUE NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Rank INT,
	LastLoginTime TIMESTAMP,
	LastLogoutTime TIMESTAMP,
	);

	CREATE TABLE Manager (
	Id VARCHAR(25) PRIMARY KEY NOT NULL,
	Phone VARCHAR(50),
	Address VARCHAR(255) NOT NULL,
	FOREIGN KEY (Id) REFERENCES User(Id),
	);

	CREATE TABLE Restaurant (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Name VARCHAR(	50) NOT NULL,
	Rating INT NOT NULL,
	Address VARCHAR(255) NOT NULL,
	LocationId INT NOT NULL,
	ManagerId VARCHAR(25) NOT NULL,
	FOREIGN KEY (LocationId) REFERENCES Location(Id),
	FOREIGN KEY (ManagerId) REFERENCES Manager(Id)
	);

	CREATE TABLE RestaurantCuisineMap (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	RestaurantId INT NOT NULL,
	CuisineId INT NOT NULL,
	FOREIGN KEY (RestaurantId) REFERENCES Restaurant(Id),
	FOREIGN KEY (CuisineId) REFERENCES Cuisine(Id)
	);

	CREATE TABLE UserCuisineMap (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserId VARCHAR(25) NOT NULL,
	CuisineId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES User(Id),
	FOREIGN KEY (CuisineId) REFERENCES Cuisine(Id)
	);

	CREATE TABLE UserLocationMap (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserId VARCHAR(25) NOT NULL,
	LocationId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES User(Id),
	FOREIGN KEY (LocationId) REFERENCES Location(Id)
	);

	CREATE TABLE Review (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	RestaurantId INT NOT NULL,
	UserId VARCHAR(25) NOT NULL,
	DateTimeAdded TIMESTAMP,
	Content VARCHAR(255),
	Upvotes INT,
	DownVotes INT,
	Category varchar(10),
	FOREIGN KEY (UserId) REFERENCES User(Id),
	FOREIGN KEY (RestaurantId) REFERENCES Restaurant(Id)
	);

	CREATE TABLE Recommendation (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserId VARCHAR(25) NOT NULL,
	RestaurantId INT NOT NULL,
	DateAdded TIMESTAMP,
	FOREIGN KEY (UserId) REFERENCES User(Id),
	FOREIGN KEY (RestaurantId) REFERENCES Restaurant(Id)
	);

	CREATE TABLE AddRestaurantRequest (
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ManagerId VARCHAR(25) NOT NULL,
	RestaurantName VARCHAR(50) NOT NULL,
	Cuisine VARCHAR(50) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	Status VARCHAR(20) NOT NULL,
	FOREIGN KEY (ManagerId) REFERENCES Manager(Id),
	);
